config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resource :orders, only: [:show, :new, :create] do
    delete :remove_plant_from
  end
  resources :categories, only: [:index, :show]
  resources :plants, only: [:index, :show] do
    post :order, on: :member
    get :details, on: :member
  end

  root :to => 'categories#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
  include SeoAttributes

  has_many :children, :foreign_key => "parent_id", :class_name => Category, dependent: :destroy
  belongs_to :parent, :class_name => Category

  has_one  :image, dependent: :destroy

  validates :name, presence: true

  scope :primary, -> { where(parent_id: nil) }
  scope :subcategories, -> { where.not(parent_id: nil) }

  paginates_per 10
end

app/models/concerns/seo_attributes.rb
# -*- encoding : utf-8 -*-
module SeoAttributes
  extend ActiveSupport::Concern

  included do
    before_save :set_seo_title
    before_save :set_seo_keywords
    before_save :set_seo_description

    serialize :seo_keywords, Array
  end

  def set_seo_title
    self.seo_title = name
  end

  def set_seo_keywords
    seo_keywords ||= []
    if seo_keywords.count <= 20
      self.seo_keywords = seo_keywords.push(name) unless seo_keywords.include?(name)
      self.seo_keywords = seo_keywords.push(name) unless seo_keywords.include?(science_name)
    end
  end

  def set_seo_description
    # 160 - recommended_length_of_seo_description
    self.seo_description = description.truncate(160, separator: " ")
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :plant
  belongs_to :category

  mount_uploader :path, ImageUploader
  # self.per_page = 10
end

app/models/order.rb
class Order < ActiveRecord::Base
  include AASM

  has_many :ordered_plants, dependent: :destroy
  has_many :plants, through: :ordered_plants

  enum state: { initial: 0, confirmed: 1, rejected: -1, completed: 2, archived: 5 }

  uniquify :token

  accepts_nested_attributes_for :ordered_plants

  validates :orderer_name, presence: true
  validates :orderer_email, presence: true
  validates_format_of :orderer_email,:with => Devise.email_regexp

  scope :expired, -> { where('updated_at > ?', 1.year.ago) }

  after_create :send_creation_email

  aasm :column => :state, enum: true do
    Order.states.keys.each.with_index do |st, i|
      if i == 0
        state st.to_sym, initial: true
      else
        state st.to_sym
      end
    end

    event :confirm, before: :summarize_price, guard: :ready_for_confirmation?,
                    after: :send_confirmed_email do
      transitions :from => :initial, :to => :confirmed
    end

    event :archive do
      transitions :from => [:rejected, :completed, :initial], :to => :archived
    end
  end

  private

  def summarize_price
    self.price_summary = ordered_plants.sum(:price)
  end

  def ready_for_confirmation?
    orderer_email.present?
  end

  def send_confirmed_email
    OrderMailer.confirmed(self.id).deliver_later
  end

  def send_creation_email
    OrderMailer.created(self.id).deliver_later
  end
end

app/models/ordered_plant.rb
class OrderedPlant < ActiveRecord::Base
  belongs_to :order
  belongs_to :plant

  # validates :order_id, presence: true
  validates :plant_id, presence: true
  validates :price,    presence: true, on: :update

  before_create :set_price

  private

  def set_price
    self.price = plant.price
  end
end

app/models/plant.rb
class Plant < ActiveRecord::Base
  include SeoAttributes

  belongs_to  :category
  has_many    :images, dependent: :destroy
  has_many    :ordered_plants
  has_many    :orders, through: :ordered_plans

  def main_image
    images.order(:weight).first
  end

  paginates_per 10
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.primary.all
  end

  def show
    @category = Category.find(params[:id])
    @subcategories = @category.children
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @order = Order.where(token: params[:token] || session[:order_token]).first
    @plants = @order ? @order.plants : Plant.where(id: session[:order])
  end

  def new
    @order = Order.new
  end

  def create
    params[:order][:ordered_plants_attributes] = session[:order].each.map { |id| { plant_id: id} }
    @order = Order.new(permitted_order)

    if @order.save
      redirect_to action: :show, token: @order.token
      reset_session
    else
      render :new
    end
  end

  def remove_plant_from
    # session[:order] -= params[:ids] if session[:order]
  end

  private

  def permitted_order
    params.require(:order).permit(:orderer_name, :orderer_email, :orderer_comment, ordered_plants_attributes: [:plant_id, :order_id])
  end

end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :color_variables, only: [:index, :show]
  before_action :get_plant, only: [:show, :details]

  def index
    @plants = Plant.order(:name).page(params[:page])
    include_search
  end

  def show
  end

  def order
    session[:order] ||= []
    session[:order].push(params[:id])
  end

  def details
  end

  private

  def get_plant
    @plant = Plant.find(params[:id]).decorate
  end

  def color_variables
    @human_blossom_colors = Plant.uniq.pluck(:blossom_color).map { |r| ['__________', r, style: "background-color: #{r}" ] }
    @human_leaf_colors = Plant.uniq.pluck(:leaf_color)
  end

  def include_search
    if params[:search]
      params[:search].each do |key, value|
        next if value.blank?
        @plants = @plants.where(key => value) if %w(blossom_color category_id).include?(key)
      end

      @plants = @plants.where('name LIKE ?', "#{params[:search][:name]}%") if params[:search][:name].present?
      @plants = @plants.where('MONTH(blossom_start) = ?', params[:search][:blossom_start]) if params[:search][:blossom_start].present?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def truncated_text(text)
    text && text.truncate(100, separator: " ")
  end

  def human_months
    I18n.t('date.month_names_prepositional').map.with_index{|month_name, index| [month_name, index+1]}
  end
end

app/views/admin/categories/_form.html.haml
- Arbre::Context.new({}, self) do  
  = semantic_form_for [:admin, resource] do |f|
    = f.inputs '' do 
      - controller.class.list_of_allowed_attr.each do |attr|
        = f.input attr

    = f.actions
  - if resource.persisted?
    = panel Image.model_name.human do
      - if resource.image
        - table_for(resource.image) do
          - column :name
          - column :path      
          - column do |c|
            - link_to('', admin_image_path(c), class: 'member_link view_link') + link_to('', edit_admin_image_path(c), class: 'member_link edit_link') + link_to('', admin_image_path(c), method: :delete, class: 'member_link delete_link')
      - else       
        - span do
          - link_to t('active_admin.views.categories.form.add_new_image'), new_admin_image_path(category_id: resource.id), class: 'link_as_button'

app/views/admin/plants/_form.html.haml
- Arbre::Context.new({}, self) do
  = semantic_form_for [:admin, resource] do |f|
    = f.inputs '' do
      - controller.class.list_of_allowed_attr.each do |attr|
        - if attr == :blossom_start
          = f.input attr, discard_year: true
        - else
          = f.input attr

    = f.actions
  - if resource.persisted?
    = panel Image.model_name.human do
      - if resource.images
        - table_for(resource.images) do
          - column :name
          - column :path
          - column do |c|
            - link_to('', admin_image_path(c), class: 'member_link view_link') + link_to('', edit_admin_image_path(c, plant_id: resource.id), class: 'member_link edit_link') + link_to('', admin_image_path(c), method: :delete, class: 'member_link delete_link')
      - span do
        - link_to t('active_admin.views.categories.form.add_new_image'), new_admin_image_path(plant_id: resource.id), class: 'link_as_button'

app/views/categories/_category.html.haml
.3u
  %section
    %a.image.full{:href => plants_path(search: { category_id: category.id })}
      %img{:alt => "", :src => asset_path(category.image.path.catalog_image.url)}/
    %p= truncated_text(category.description)
    %a.button{:href => plants_path(search: { category_id: category.id }) }
      = t('views.shared.read_more')

app/views/categories/index.html.haml
%header
  %h2
    Каталог
.row
  = render @categories, cache: true

app/views/layouts/_header.html.haml
.container
  / Logo
  #logo
    %h1
      = link_to Settings.site_title, root_path
    -#%span Design by TEMPLATED
  / Nav
  %nav#nav
    %ul
      - [{ name: t('views.layout.navpanel.homepage'), path: root_path },
         { name: t('views.layout.navpanel.categories'), path: categories_path },
         { name: t('views.layout.navpanel.plants'), path: plants_path },
         { name: t('views.layout.navpanel.basket'), path: orders_path }].each do |hash|
        %li{ class: current_page?(hash[:path]) ? 'active' : nil }
          = link_to hash[:name], hash[:path]

app/views/layouts/application.html.haml
!!!
%html
  %head
    - cache do
      = tag :meta, :charset => ::Flower::Application.config.encoding
      = tag :meta, :'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1'
      = tag :meta, :name => 'viewport', :content => 'width=device-width, height=device-height'
      = tag :meta, :'http-equiv' => :msthemecompatible, :content => :no
      = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
      = stylesheet_link_tag 'basic'
      = stylesheet_link_tag 'galleriffic-5'
      = stylesheet_link_tag 'bootstrap_and_overrides'
      -#= stylesheet_link_tag 'black'
      %link{:href => "http://fonts.googleapis.com/css?family=Oxygen:400,300,700", :rel => "stylesheet", :type => "text/css"}/
    = csrf_meta_tags    
    = display_meta_tags :site => Settings.site_title, :separator => '-', :og => {:title => :title}

    /[if lt IE 8]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = javascript_include_tag "application"
    /[if lte IE 8] <link rel="stylesheet" href="css/ie/v8.css" />
    /[if lte IE 9] <link rel="stylesheet" href="css/ie/v9.css" />
  %body   
    #header
      = render 'layouts/header'        
    #main
      .container
        = yield
    #copyright
      .container
        design:
        %a{:href => "http://templated.co"} TEMPLATED   
        developer:     
        %a{:href => "https://www.linkedin.com/pub/anton-bogarsukov/49/438/568"} Anton

app/views/orders/_form.html.haml
= simple_form_for order do |f|
  -#= f.label :orderer_name, 'Ваше имя'
  = f.input :orderer_name
  -#= f.label :orderer_email, 'Почтовый ящик'
  = f.input :orderer_email, as: :email
  -#= f.label :orderer_comment, 'Любая дополнительная информация'
  = f.input :orderer_comment, as: :text
  = f.submit 'Подтвердить', class: 'button'

app/views/orders/new.html.haml
= render 'form', order: @order

app/views/orders/remove_plant_from.js.erb
<% params[:ids].each do |id| %>
  $('.plant_<%= id %>').remove();
<% end %>
if($('table tbody tr').length == 1){
  $('table tbody tr.info').remove();
}
else{
  var sum = 0.0;
  $('table .price').each(function(){
    sum += parseFloat($(this).html());
  })
  $('tr.info .total_price').html(sum);
}

app/views/orders/show.html.haml
.row
  / Content
  .8u.skel-cell-important
    %section#content
      %table.table.table-striped.table-hover.table-responsive
        %thead
          %th #
          %th= Plant.human_attribute_name('name')
          %th= Plant.human_attribute_name('price')
          - unless @order && @order.persisted?
            %th
        %tbody
          - total = 0.0
          - @plants.each.with_index do |plant, i|
            %tr.presentable{ id: dom_id(plant)}
              %th= i + 1
              %th= link_to(plant.name, plant_path(plant))
              %th.price= plant.price
              - total += plant.price if plant.price
              - unless @order && @order.persisted?
                %th= link_to(t('views.shared.order.delete'), remove_plant_from_orders_path(ids: [plant.id]), remote: true, method: :delete)
          %tr.info
            %th Итого
            %th
            %th.total_price= total
            - unless @order && @order.persisted?
              %th= link_to(t('views.shared.order.delete_all'), remove_plant_from_orders_path(ids: [session[:order]]), remote: true, method: :delete)
    - if @order && @order.persisted?
      %header
        %h2
          %p
            Заказ создан
        %h3
          %p
            = "Ув #{@order.orderer_name}, проверте свою почту #{@order.orderer_email}"
    - else
      = link_to(t('views.shared.order.edit'), new_orders_path, class: 'button')

  / Sidebar
  #sidebar.4u
    %section

:javascript
  jQuery(document).ready(function($) {
    $('table tr.presentable').on('mouseover', function(){
      $.get("/plants/"+$(this).attr('id').replace('plant_', '') + '/details')
    });
  });

app/views/plants/_plant.html.haml
.3u.float_left.margined
  = render 'plant_block', plant: plant

app/views/plants/_plant_block.html.haml
%section
  %h2
    = plant.name.capitalize
  - if plant.images.exists?
    %a.image.full{:href => plant_path(plant)}
      %img{:alt => "", :src => asset_path(plant.main_image.path.url)}/
  %p= truncated_text(plant.description)
  %a.button{:href => plant_path(plant)}
    = t('views.shared.read_more')

app/views/plants/_sidebar.html.haml
#sidebar.4u
  %section
    %header
      %h2 Поиск
      %span.byline
        - ('А'..'Я').each do |letter|
          = link_to letter, plants_path(search: { name: letter }.merge((params[:search] || {}).except(:name)) )
    = form_for(:search, url: plants_path, method: :get) do |f|
      = f.label :name, 'Названиие или его часть'
      = f.text_field(:name, value: params[:search] && params[:search][:name])
      = f.label :blossom_start, 'Начало цветения в'
      = f.select(:blossom_start, options_for_select(human_months, params[:search] && params[:search][:blossom_start]), include_blank: true)
      = f.label :leaf_color, 'Цвет листьев'
      = f.select(:leaf_color, options_for_select(@human_leaf_colors, params[:search] && params[:search][:leaf_color]), include_blank: true )
      = f.label :blossom_color, 'Окрас цветения'
      = f.select(:blossom_color, options_for_select(@human_blossom_colors, params[:search] && params[:search][:blossom_color]), include_blank: true)

      = f.submit 'Искать', class: 'button'

app/views/plants/details.js.erb
$('#sidebar').html('<%= escape_javascript render 'plant_block', plant: @plant %>');

app/views/plants/index.html.haml
%header
  %h2
    Растения
.row
  .8u.skel-cell-important
    - if @plants.any?
      = render @plants, cache: true
    - else
      %p
        К сожалению по вашему запросу ничего не найдено.
  = render 'sidebar'

app/views/plants/order.js.erb
$('a.order_button')
    .addClass('disabled')
    .html('<%= I18n.t('views.shared.order.disabled')%>');

app/views/plants/show.html.haml
:ruby
  set_meta_tags title: @plant.seo_title
  set_meta_tags description: @plant.seo_description
  set_meta_tags keywords: @plant.seo_keywords.join(',')
.row
  / Content
  .8u.skel-cell-important
    %section#content
      %header.inline_block
        %h2.float_left
          = @plant.name
        - if @plant.science_name.present?
          %span.byline
            = @plant.science_name
        = link_to(t("views.shared.order.#{@plant.disabled}"), order_plant_path(@plant),
          class: "button order_button btn #{@plant.disabled}", remote: true, method: :post)
      #page
        #container
          .navigation-container
            #thumbs.navigation
              %a.pageLink.prev{:href => "#", :style => "visibility: hidden;", :title => "Previous Page"}
              %ul.thumbs.noscript
                - @plant.images.each do |image|
                  %li
                    %a.thumb{:href => asset_path(image.path.main.url), :name => "leaf", :title => "Title #0"}
                      %img{:alt => "Title #0", :src => asset_path(image.path.thumb.url)}/
          .content
            .slideshow-container
              #controls.controls
              #loading.loader
              #slideshow.slideshow
            #caption.caption-container
              .caption
                -#.image-title
                -#  = @plant.name
                - @plant.attribute_names_to_display.each do |attr|
                  .image-desc
                    = @plant.class.human_attribute_name(attr)
                    = ':'
                    = @plant.send(attr)

              .photo-index
          / End Gallery Html Containers
          %div{:style => "clear: both;"}
  / Sidebar
  = render 'sidebar'

#fullImage.modal.fade{"aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
  .custom-modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×

:javascript
  jQuery(document).ready(function($) {
    $('#fullImage').on('show.bs.modal', function (event) {
      var src = $('.advance-link').find('img').attr('src');
      $('#fullImage .modal-header img').remove();

      image = $('<img src="'+src.replace('main_', '')+'">')
        .load(function(){
          var padding = parseInt($('#fullImage .modal-header').css('padding'));
          $('#fullImage .custom-modal-dialog').css('width', parseInt(this.width) + padding*2);
        })
        .appendTo('#fullImage .modal-header');


    })

    // We only want these styles applied when javascript is enabled
    $('div.content').css('display', 'block');

    // Initially set opacity on thumbs and add
    // additional styling for hover effect on thumbs
    var onMouseOutOpacity = 0.67;
    $('#thumbs ul.thumbs li, div.navigation a.pageLink').opacityrollover({
      mouseOutOpacity:   onMouseOutOpacity,
      mouseOverOpacity:  1.0,
      fadeSpeed:         'fast',
      exemptionSelector: '.selected'
    });

    // Initialize Advanced Galleriffic Gallery
    var gallery = $('#thumbs').galleriffic({
      delay:                     2500,
      numThumbs:                 10,
      preloadAhead:              10,
      enableTopPager:            false,
      enableBottomPager:         false,
      imageContainerSel:         '#slideshow',
      controlsContainerSel:      '#controls',
      captionContainerSel:       '#caption',
      loadingContainerSel:       '#loading',
      renderSSControls:          true,
      renderNavControls:         false,
      playLinkText:              'Запустить показ',
      pauseLinkText:             'Остановить показ',
      nextPageLinkText:          'Next &rsaquo;',
      prevPageLinkText:          '&lsaquo; Prev',
      enableHistory:             true,
      autoStart:                 false,
      syncTransitions:           true,
      defaultTransitionDuration: 900,
      onSlideChange:             function(prevIndex, nextIndex) {
        // 'this' refers to the gallery, which is an extension of $('#thumbs')
        this.find('ul.thumbs').children()
          .eq(prevIndex).fadeTo('fast', onMouseOutOpacity).end()
          .eq(nextIndex).fadeTo('fast', 1.0);

        // Update the photo index display
        this.$captionContainer.find('div.photo-index')
          .html('Photo '+ (nextIndex+1) +' of '+ this.data.length);
      },
      onPageTransitionOut:       function(callback) {
        this.fadeTo('fast', 0.0, callback);
      },
      onPageTransitionIn:        function() {
        var prevPageLink = this.find('a.prev').css('visibility', 'hidden');
        var nextPageLink = this.find('a.next').css('visibility', 'hidden');

        // Show appropriate next / prev page links
        if (this.displayedPage > 0)
          prevPageLink.css('visibility', 'visible');

        var lastPage = this.getNumPages() - 1;
        if (this.displayedPage < lastPage)
          nextPageLink.css('visibility', 'visible');

        this.fadeTo('fast', 1.0);
      }
    });

    /**************** Event handlers for custom next / prev page links **********************/

    gallery.find('a.prev').click(function(e) {
      gallery.previousPage();
      e.preventDefault();
    });

    gallery.find('a.next').click(function(e) {
      gallery.nextPage();
      e.preventDefault();
    });

  });